
    create sequence person_seq start with 1 increment by 50;

    create table contact (
        data_contact date,
        consultant_id bigint,
        customer_id bigint,
        id bigint generated by default as identity,
        description varchar(255),
        title varchar(255),
        primary key (id)
    );

    create table person (
        id bigint not null,
        dtype varchar(31) not null,
        about varchar(255),
        cpf varchar(255),
        email varchar(255),
        name varchar(255),
        specialization varchar(255),
        links varchar(255) array,
        primary key (id)
    );

    create table profiles (
        profiles integer,
        person_id bigint not null
    );

    alter table if exists contact
       add constraint FKptusl2nx3fk8mqf17aw24v7cj
       foreign key (consultant_id)
       references person;

    alter table if exists contact
       add constraint FKjupn76w9m19t3w8s6wcjpkun8
       foreign key (customer_id)
       references person;

    alter table if exists profiles
       add constraint FK3mrk7kyi9yeah63o5pnykphqs
       foreign key (person_id)
       references person;
